### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Cecca** [Cecca/workloads-generation#1]
# Roadmap

## The goal

We want to
- generate datasets of different difficulty (for different definitions of difficulty)
- assess that indeed different indices require to invest work proportional to the difficulty of the queries

## Pain points

- [x] #8
- Our configuration is currently scattered across several different sources: `parameters.py`, `config.yaml`, `bin_config.csv`. We should converge to a uniform format that is flexible and easy to use. 
	- The [paramspace Snakemake feature](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#parameter-space-exploration) (automatically) creates folder structures that are so deep that they are basically opaque. Furthermore it is not very flexible: being dataframe based it requires that hall configurations have the same parameters. This breaks when we have multiple ways of generating workloads, for instance
	- `config.yaml` is another builtin feature of snakemake and with some work allows to generate all combinations of parameters. The main problem is that at some point we will want to exclude some parameter combination from the cartesian product, and YAML has no way of doing that
	- `bin_config.csv` as used right now has the problem that we use the indices of the rows as identifiers for snakemake-managed files. This breaks as soon as we change the configuration associated to one already-existing line. Suppose that we run the configuration associated to line `0` (which in the snakemake pipeline then creates several files) and then we change it. Snakemake will not re-run the jobs because the files (from the old execution) are already there with the right name.
- Our snakemake file has grown a bit unwieldy and should go on a diet. There are for sure rules that are not used and that should be removed.

## Things to do

- [ ] Add a generator for synthetic queries based on random noise
- [ ] Integrate other indices, and evaluate their performance (which indices? which metric?)

## Questions to answer

- [ ] Which method for generating queries is best (and what does best even mean?)
- [ ] Do other indices really have a hard time on hard queries?
- [ ] Which difficulty metrics are most effective in actually building difficult queries?
